name: AWS DEPLOY TO STAGING
# turn off deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_PW: ${{ secrets.AWS_DB_PW}}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      COHERE_KEY: ${{ secrets.COHERE_KEY }}
      OPENAI_SECRET_KEY: ${{ secrets.OPENAI_SECRET_KEY}}
      OPENAI_ASSISTANT: ${{ secrets.OPENAI_ASSISTANT}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: '22.4.1'
      - run: npm install

      - run: |
          touch .env
          echo DB_HOST = "$DB_HOST" >> .env
          echo DB_PW = "$DB_PW" >> .env
          echo DB_USER = "$DB_USER" >> .env
          echo DB_NAME = "$DB_NAME" >> .env
          echo SECRET_KEY = "$SECRET_KEY" >> .env
          echo COHERE_KEY = "$COHERE_KEY" >> .env
          echo OPENAI_SECRET_KEY = "$OPENAI_SECRET_KEY" >> .env
          echo OPENAI_ASSISTANT = "$OPENAI_ASSISTANT" >> .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "ec2-34-210-247-213.us-west-2.compute.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/resume-generation-backend"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@ec2-34-210-247-213.us-west-2.compute.amazonaws.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/resume-generation-backend
            npm install
            sudo systemctl stop resume-generation-backend
            sudo cp resume-generation-backend.service /lib/systemd/system/resume-generation-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start resume-generation-backend
